# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GoogleSheetsDownloader
                                 A QGIS plugin
 This plugin downloads data from Google Sheets
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-06-04
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Group B - FGIS 2021
        email                : marek.hoffmann@fsv.cvut.cz, monika.krizova@fsv.cvut.cz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, pyqtSignal
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .google_sheets_downloader_dockwidget import GoogleSheetsDownloaderDockWidget
from qgis.core import QgsApplication, QgsMessageLog, QgsProject, QgsVectorLayer, Qgis
from sp_gdrive import downloadSpreadsheet
from qgis.utils import iface

import os.path, sys


class GoogleSheetsDownloader:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GoogleSheetsDownloader_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Google Sheets Downloader')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'GoogleSheetsDownloader')
        self.toolbar.setObjectName(u'GoogleSheetsDownloader')

        #print "** INITIALIZING GoogleSheetsDownloader"

        self.pluginIsActive = False
        self.dockwidget = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GoogleSheetsDownloader', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/google_sheets_downloader/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Google Sheets Downloader'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING GoogleSheetsDownloader2"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD GoogleSheetsDownloader2"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Google Sheets Downloader'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING GoogleSheetsDownloader2"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = GoogleSheetsDownloaderDockWidget()
                self.dockwidget.load.clicked.connect(self.on_load)

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

    def on_load(self):
        """
        Start after pressing "load", assigning values from the plugin to the variables.
        Call functions for downloading data and create new QGIS layer.
        """
        self.filepath = os.path.dirname(__file__)

        # input data
        self.filename = self.dockwidget.typeName.text()
        self.Xcol = self.dockwidget.typeX.text()
        self.Ycol = self.dockwidget.typeY.text()
        self.CRS = self.dockwidget.selectCRS.crs().authid()

        try:
            downloadSpreadsheet(self.filepath, self.filename)
        except IndexError:
            iface.messageBar().pushMessage('No such file "{}" located on your Google Drive account.'.format(self.filename), duration=3, level=Qgis.Critical)
        else:
            self.loadVector(self.filepath, self.filename, self.Xcol, self.Ycol, self.CRS)

    def loadVector(self, filepath, filename, X, Y, CRS):
        """
        Create new point layer from the csv file.

        :param filepath: path to the plugin/project
        :param filename: name of the sheet on GDrive
        :param X: name of the column with X coordinate
        :param Y: name of the column with Y coordinate
        :param CRS: coordinate reference system
        """
        uri = "file:///" + filepath + "/sheets/" + filename + ".csv" + "?encoding={}&delimiter={}&xField={}&yField={}&crs={}&decimalPoint={}".format(
            "UTF-8", ",", X, Y, CRS, ",")

        new_layer = QgsVectorLayer(uri, filename, "delimitedtext")

        if not new_layer.isValid():
            iface.messageBar().pushMessage('Invalid coordinate columns parameters.', duration=3, level=Qgis.Critical)
        elif not self.CRS:
            QgsProject.instance().addMapLayer(new_layer)
            iface.messageBar().pushMessage('No coordinate system assigned.', duration=3, level=Qgis.Warning)
        else:
            QgsProject.instance().addMapLayer(new_layer)
            iface.messageBar().pushMessage('Layer "{}" loaded.'.format(filename), duration=3, level=Qgis.Success)
